apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    tier: backend
spec:
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: nginx
    tier: backend
  externalIPs:
    - 180.151.83.179
