apiVersion: v1
kind: Pod
metadata:
  name: postgres-db-pod
  labels:
    db: postgres-db
    type: postgres-database
spec:
  containers:
    - name: postgres-db-container
      image: postgres:9.4
      ports:
        - containerPort: 5432
