apiVersion: v1
kind: Pod
metadata:
  name: redis-db-pod
  labels:
    db: redis-db
    type: redis-database
spec:
  containers:
    - name: redis-db-container
      image: redis
      ports:
        containerPort: 6379

