apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    app: result-app
    type: result
spec:
  containers:
    - name: result-app-container
      image: docker/example-voting-app-result
      ports:
        containerPort: 80

