apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    name: result-app-deployment
    type: demo-voting-app
spec:
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: result-app
          image: docker/example-voting-app-result
          ports:
            - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      app: result-app
      type: result
