apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    app: voting-app
    type: voting
spec:
  containers:
    - name: voting-app-container
      image: docker/example-voting-app-vote
      ports:
        containerPort: 80
